# Generated by Django 4.1.7 on 2023-03-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myarray',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
