# Generated by Django 4.1.7 on 2023-03-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_myarray_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myarray',
            name='status',
            field=models.IntegerField(default=False),
        ),
    ]
